name:                H-R-Tracing
version:             0.1.0.0
github:              "githubuser/H-R-Tracing"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/H-R-Tracing#readme>

dependencies:
- base >= 4.7 && < 5
- numeric-limits >= 0.1.0.0
- bytestring
- random 
- split
- deepseq
- parallel

library:
  source-dirs: src

executables:
  H-R-Tracing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N4 -s"'
    - -fllvm -optlo-O3 -optl-ffast-math -funfolding-use-threshold1000
    dependencies:
    - H-R-Tracing


tests:
  H-R-Tracing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - H-R-Tracing
    - tasty 
    - tasty-hunit
    - tasty-smallcheck
    - tasty-quickcheck
